name: CD

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  cd:
    name: "Continuous delivery"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: | 
            npm run build
